PROJECTS_PER_PAGE = 12
USERS_PER_PAGE = 12 

SKILLS_AUTOCOMPLETE_LIMIT = 10

AVATAR_SIZE = 200
AVATAR_FONT_SIZE = 100

AVATAR_UPLOAD_DIR = 'avatars/'

PASSWORD_MIN_LENGTH = 8

GITHUB_URL = 'github.com'